namespace chat.Models
{
    public class ChatRoom
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string RoomId { get; set; } // The UUID generated by the frontend
        public string Name { get; set; } // Optional: a friendly name for the room
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public Guid CreatedById { get; set; } // Reference to the user who created it
        public User CreatedBy { get; set; } // Navigation property
    }
}